import './globals.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'PathPerfect',
  description: 'Generated by create next app',
}

/**
 * This is the `RootLayout` component, serving as the root layout for your Next.js application.
 * It sets the HTML lang attribute, applies the Inter font with the Latin subset, and renders the children components.
 *
 * @param {Object} props - The component's properties.
 * @param {ReactNode} props.children - The child components to be rendered within the layout.
 * @returns {JSX.Element} The JSX element representing the `RootLayout` component.
 */
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
